= XYZ Reader Starter Code

This repository stores the XYZ Reader app made for Udacity's Android Nanodegree.

## Project Overview
In this project, I redesigned an app to follow the Material Design guidelines and translate a set of static design mocks to a living and breathing app.

Why this Project?
This project gives an opportunity to improve an app’s design, a vital skill for building apps users will love. It also replicates a common developer task of updating and changing an app's design as new standards are released.

* Understand the fundamentals of Android design.
* Apply Material Design guidelines to an mobile application.
* Separate an interface into surfaces.
* Effectively use transitions and motion.

The starter app has design flaws and inconsistencies, as well as overloaded and unecessary java code which makes it visually unpleant and slow resulting in a bad user experience.

The updated app uses a modern material desing, CoordinatorLayout, CollapsingToolbarLayout, the necessary behaviours and childs, updated java code to make it faster and its usage more pleasant. 



